# Generated by Django 5.2.16 on 2026-07-23 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_photo_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('digital', 'Tribute Digital — $149'), ('print', 'Tribute Print — $99'), ('complete', 'Complete Tribute — $199')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid — Processing'), ('processing', 'In Production'), ('completed', 'Completed'), ('shipped', 'Shipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('shipping_name', models.CharField(blank=True, max_length=200)),
                ('shipping_address', models.TextField(blank=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100)),
                ('shipping_state', models.CharField(blank=True, max_length=100)),
                ('shipping_zip', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='slideshows/')),
                ('music_choice', models.CharField(blank=True, default='gentle-piano', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order')),
                ('photos', models.ManyToManyField(blank=True, to='main.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
