# Generated by Django 5.2.16 on 2026-07-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_photo_id_order_slideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid — Processing'), ('processing', 'In Production'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tier',
            field=models.CharField(choices=[('digital', 'Tribute Package — $149')], max_length=20),
        ),
    ]
