# Generated by Django 5.2.16 on 2026-07-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_order_status_alter_order_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='slideshows/', verbose_name='Funeral Flyer PDF'),
        ),
    ]
