# Generated by Django 5.2.16 on 2026-07-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='burial_place',
            field=models.CharField(blank=True, max_length=300, verbose_name='Burial / Interment Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Passing'),
        ),
        migrations.AddField(
            model_name='order',
            name='deceased_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Deceased's Full Name"),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_song',
            field=models.CharField(blank=True, max_length=200, verbose_name='Preferred Music/Song'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_location',
            field=models.CharField(blank=True, help_text='Church, funeral home, or venue name and address', max_length=300, verbose_name='Service Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_time',
            field=models.CharField(blank=True, help_text='e.g. 11:00 AM', max_length=50, verbose_name='Time of Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(blank=True, help_text='e.g. Funeral Service, Memorial Service, Celebration of Life', max_length=100, verbose_name='Type of Service'),
        ),
        migrations.AddField(
            model_name='order',
            name='special_notes',
            field=models.TextField(blank=True, help_text="Any other details you'd like us to know", verbose_name='Additional Notes'),
        ),
    ]
