# Generated by Django 5.2.16 on 2026-07-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_burial_place_order_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic Tribute — $49'), ('digital', 'Tribute Package — $149')], max_length=20),
        ),
    ]
