# Generated by Django 5.2.16 on 2026-07-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic Tribute — $49'), ('digital', 'Tribute Package — $89')], max_length=20),
        ),
    ]
