# Generated by Django 5.2.16 on 2026-07-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic Tribute — $49.99'), ('digital', 'Tribute Package — $89.99')], max_length=20),
        ),
    ]
