# Generated by Django 5.2.16 on 2026-08-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic Tribute — $49.99'), ('digital', 'Tribute Package — $74.99')], max_length=20),
        ),
    ]
